---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: python
    tag: 2.7-slim

inputs:
  - name: concourse_tasks

run:
  path: python
  args: ["concourse_tasks/setup_nsp.py","--configure_basic","-c","nsp_config.json"]
