---
resources:
- name: concourse_tasks
  type: git
  source:
    uri: https://github.com/sandeep6189/concourse_tasks.git

jobs:
- name: deploy_nsp
  public: true
  plan:
  - get: concourse_tasks
  - aggregate:
    - task: deploy_hcm
      file: concourse_tasks/tasks/deploy_hcm.yml
    - task: deploy_nsp
      file: concourse_tasks/tasks/deploy_nsp.yml

- name: wait_for_services
  public: true
  plan:
  - get: concourse_tasks
    passed: [deploy_nsp]
    trigger: true
  - task: time_wait
    file: concourse_tasks/tasks/wait_until_service_up.yml

- name: add_vc_nsx_proxy_details
  public: true
  plan:
  - get: concourse_tasks
    passed: [wait_for_services]
    trigger: true
  - task: configure_basic
    file: concourse_tasks/tasks/configure_basic.yml

- name: restart_nsp_services
  public: true
  plan:
  - get: concourse_tasks
    passed: [add_vc_nsx_proxy_details]
    trigger: true
  - task: restart_service
    file: concourse_tasks/tasks/restart_service.yml

- name: network_and_fleet_config
  public: true
  plan:
  - get: concourse_tasks
    passed: [restart_nsp_services]
    trigger: true
  - task: config_network_and_fleet
    file: concourse_tasks/tasks/api_config.yml

- name: basic_hcm_config
  public: true
  plan:
  - get: concourse_tasks
    passed: [network_and_fleet_config]
    trigger: true
  - task: hcm_basic_config
    file: concourse_tasks/tasks/hcm_basic.yml
